CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY,
    instance_id UUID,
    aud VARCHAR,
    role VARCHAR,
    email VARCHAR UNIQUE,
    encrypted_password VARCHAR,
    email_confirmed_at TIMESTAMPTZ,
    invited_at TIMESTAMPTZ,
    confirmation_token VARCHAR,
    confirmation_sent_at TIMESTAMPTZ,
    recovery_token VARCHAR,
    recovery_sent_at TIMESTAMPTZ,
    email_change_token_new VARCHAR,
    email_change VARCHAR,
    email_change_sent_at TIMESTAMPTZ,
    last_sign_in_at TIMESTAMPTZ,
    raw_app_meta_data JSONB,
    raw_user_meta_data JSONB,
    is_super_admin BOOLEAN,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    phone TEXT,
    phone_confirmed_at TIMESTAMPTZ,
    phone_change TEXT,
    phone_change_token VARCHAR,
    phone_change_sent_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    email_change_token_current VARCHAR,
    email_change_confirm_status INT2,
    banned_until TIMESTAMPTZ,
    reauthentication_token VARCHAR,
    reauthentication_sent_at TIMESTAMPTZ,
    is_sso_user BOOLEAN,
    deleted_at TIMESTAMPTZ,
    is_anonymous BOOLEAN
);
