import json

filepath = "c:/Users/mirko/Documents/Ibiza Beyond/invenio_supabase_sync.json"

with open(filepath, "r", encoding="utf-8") as f:
    data = json.load(f)

nodes_dict = {n["name"]: n for n in data["nodes"]}

# 1. The problem is that the HTTP node "Upsert Properties to Supabase" returns the Supabase response,
#    which wipes out the `prices` and `properties` arrays generated by "Prepare Supabase Data".
#    So, "Split Prices" has no `prices` array to split.

# FIX: Change the routing. 
# "Prepare Supabase Data" will branch into TWO parallel paths:
# Path A: Upsert Properties to Supabase
# Path B: Split Prices -> Loop Prices -> Upsert Prices to Supabase

data["connections"] = {
    "Schedule Trigger": {
        "main": [
            [{"node": "Invenio - Get Villas", "type": "main", "index": 0}]
        ]
    },
    "Invenio - Get Villas": {
        "main": [
            [{"node": "Invenio - Get Prices", "type": "main", "index": 0}]
        ]
    },
    "Invenio - Get Prices": {
        "main": [
            [{"node": "Prepare Supabase Data", "type": "main", "index": 0}]
        ]
    },
    "Prepare Supabase Data": {
        "main": [
            [
                {"node": "Upsert Properties to Supabase", "type": "main", "index": 0},
                {"node": "Split Prices", "type": "main", "index": 0}
            ]
        ]
    },
    "Upsert Properties to Supabase": {
        "main": [
            []
        ]
    },
    "Split Prices": {
        "main": [
            [{"node": "Loop Prices", "type": "main", "index": 0}]
        ]
    },
    "Loop Prices": {
        "main": [
            [{"node": "Upsert Prices to Supabase", "type": "main", "index": 0}]
        ]
    },
    "Upsert Prices to Supabase": {
        "main": [
            [{"node": "Loop Prices", "type": "main", "index": 0}]
        ]
    }
}

# 2. In "Split Prices", we need to ensure the fieldToSplitOut is correct. 
# The input to "Split Prices" comes directly from "Prepare Supabase Data" now.
# The code node output is: `[{ json: { properties: properties, prices: prices } }]`.
# So "prices" is correct for fieldToSplitOut.

with open(filepath, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=4)

print("Workflow routing updated successfully.")
